#define INTERRUPT0_SENCE_MODE RISING_EDGE
#define INTERRUPT0_SENCE_MODE FALLING_EDGE
#define INTERRUPT0_SENCE_MODE ON_CHANGE
#define INTERRUPT0_SENCE_MODE LOW_LEVEL
#define INTERRUPT1_SENCE_MODE RISING_EDGE
#define INTERRUPT1_SENCE_MODE FALLING_EDGE
#define INTERRUPT1_SENCE_MODE ON_CHANGE
#define INTERRUPT1_SENCE_MODE LOW_LEVEL
