#ifndef  SPI_CONFIG_H
#define SPI_CONFIG_H

#define SPI_INTERRUPT_ENABLE ENABLE
#define SPI_ENABLE	DISABLE
#define DATA_ORDER LSB
#define SPI_MODE SLAVE
#define CLOCK_POLARITY RISING_EDGE
#define CLOCK_PHASE SAMPLE
#define CLK_RATE FEQ_DIV_4



#endif
